# Generated by Django 5.1.2 on 2024-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('cam_north_link', models.CharField(max_length=255, null=True)),
                ('cam_south_link', models.CharField(max_length=255, null=True)),
                ('out_traffic_level', models.CharField(max_length=50, null=True)),
                ('in_traffic_level', models.CharField(max_length=50, null=True)),
                ('lane_us', models.CharField(max_length=255, null=True)),
                ('lane_status_mex', models.CharField(max_length=255, null=True)),
                ('us_lane_type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
